name: Deploy Remotely
on:
  push:
    branches: [ master ]
 
jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm install
    - run: CI=false npm run build
    - name: Test SSH Connection
      run: ssh -i ~/.ssh/deploy_key -p ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo 'Connection successful'"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
    - name: Transfer Build Folder on EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "dist/"
        TARGET: ${{ secrets.DEPLOY_TARGET }}
      with:
        args: "-v"  # Add verbose flag for detailed output

